### ISSUE TITLE
I am getting "ContainerNotFound" errors

### ISSUE THREAD

**Issue by adamcarr** [bestander/gulp-deploy-azure-cdn#2]
When I run this locally, I get...

```
Message:
    The specified container does not exist.
RequestId: 00000000-0000-0000-0000-000000000000
Time:2015-08-11T19:47:40.8942115Z
Details:
    code: ContainerNotFound
    statusCode: 404
    requestId: 00000000-0000-0000-0000-000000000000
```

I know that things are connected correctly because if I delete the container via the portal and then run this, it will create the container for me, and then still fails when trying to upload the files. 

Here is my configuration.

```
gulp.task('azure', function () {
    return gulp.src(['cdn/**/*', 'config.js'], {
        base: 'node_modules/deploy-azure-cdn'
    }).pipe(deployCdn({
        containerName: 'statics',
        serviceOptions: ['xxx', 'yyy'],
        folder: '',
        containerOptions:  {publicAccessLevel : 'blob'},
        zip: true,
        deleteExistingBlobs: false,
        concurrentUploadThreads: 10,
        metadata: {
            cacheControl: 'public, max-age=31530000',
            cacheControlHeader: 'public, max-age=31530000'
        },
        testRun: false
    }));
});
```
